services:
  postgres:
    image: astraonline/postgrespgvector:2024
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bases
      - TZ=America/Sao_Paulo
      - PG_MAX_CONNECTIONS=500
    ports:
      - 5432:5432
    volumes:
      - ./dados-postgres:/var/lib/postgresql/data
